sudo: required

services:
- docker

arch:
  packages:
  - postgresql
  script:
  - sudo -H -u postgres 'initdb --locale $LANG -E UTF8 -D /var/lib/postgres/data'
  - sudo -H -u postgres 'pg_ctl -s -D /var/lib/postgres/data start -w -t 120'
  - makepkg -fci --noconfirm
  - env REGRESS_OPTS=--user=postgres make installcheck

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
