sudo: required

services:
- docker

arch:
  packages:
  - postgresql
  script:
  - makepkg -fci --noconfirm && sudo systemctl restart postgresql.service && env REGRESS_OPTS=--user=postgres make installcheck

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
